# Please note we are using Docker Compose version 3
version: '3'
services:
  db:
    image: postgres:13
    restart: always
    container_name: analyzer_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: analyzer
      POSTGRES_PASSWORD: analyzer
    volumes:
      - ./postgres:/var/lib/postgresql/data
