spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    username: postgres
    password: analyzer

  jpa:
    show-sql: false
    properties:
      hibernate:
        ejb.interceptor.session_scoped: zieit.kononenko.analyzer.api.integration.config.HibernateInterceptor

logging:
  level:
    root: info

server:
  port: 8085