spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    username: postgres
    password: analyzer

logging:
  level:
    root: info


spark:
  postgres:
    jars:
      - ./jars/postgresql-42.5.1.jar
    master: spark://127.0.0.1:7077
    maxExecutors: 1
    coresPerExecutor: 1
    memory: 4g
    retryWait: 3
    maxRetries: 3

    url: jdbc:postgresql://localhost:5432/analyzer
    username: postgres
    password: analyzer
    database: analyzer

server:
  port: 8090
